# Generated by Django 4.2.18 on 2025-01-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
