# Generated by Django 4.2.18 on 2025-01-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
